In [1]:
import scanpy as sc
import pandas as pd
import numpy as np
from scipy import sparse
import anndata as ad

#### After filtering
v228_1 nur obs - in var und counts weiterhin v227_2

In [2]:
df_anno_new = pd.read_csv('h228_1_qc_integrated_rpca_cellanno_FILTEREDqc_FILTEREDpureCells.txt',sep='\t',index_col = 0)
MA_obs = pd.read_csv('v227_2_MA_obs.csv',index_col = 0)
PR_obs = pd.read_csv('v227_2_PR_obs.csv',index_col = 0)
MA_obs_keep = pd.merge(MA_obs,df_anno_new[['uniform_name_overview_keep']], left_index=True, right_index=True, how='left')
PR_obs_keep = pd.merge(PR_obs,df_anno_new[['uniform_name_overview_keep']], left_index=True, right_index=True, how='left')

/tmp/ipykernel_279053/3282151679.py:1: DtypeWarning: Columns (8,9,11,12,13,14,15,16,18,19,21,22,23,24,25,26,27,29,30,31,32,33,34,35,37,39,40,41,42,43,44,67,69,78,79,80,96,97,100,101,102,106,116) have mixed types. Specify dtype option on import or set low_memory=False.
  df_anno_new = pd.read_csv('h228_1_qc_integrated_rpca_cellanno_FILTEREDqc_FILTEREDpureCells.txt',sep='\t',index_col = 0)
/tmp/ipykernel_279053/3282151679.py:2: DtypeWarning: Columns (8,9,11,12,13,14,15,16,18,19,21,22,23,24,25,26,27,29,30,31,32,33,34,35,37,39,40,41,42,43,44,67,69,78,79,80,96,97,100,101,102,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  MA_obs = pd.read_csv('v227_2_MA_obs.csv',index_col = 0)
/tmp/ipykernel_279053/3282151679.py:3: DtypeWarning: Columns (8,9,11,12,13,14,15,16,18,19,21,22,23,24,25,26,27,29,30,31,32,33,34,35,37,39,40,41,42,43,44,67,69,78,79,80,96,97,100,101,102,107,108) have mixed types. Specify dtype option on import or set low_memory=False.
  PR_obs = pd.read_csv('v227_2_PR_obs.csv',index_col = 0)

In [3]:
MA_obs_keep.to_csv('v228_1_MA_obs.csv')
PR_obs_keep.to_csv('v228_1_PR_obs.csv')

In [2]:
test_MA = pd.read_csv('v228_1_MA_obs.csv',index_col = 0)

/tmp/ipykernel_1353763/3895195511.py:1: DtypeWarning: Columns (8,9,11,12,13,14,15,16,18,19,21,22,23,24,25,26,27,29,30,31,32,33,34,35,37,39,40,41,42,43,44,67,69,78,79,80,96,97,100,101,102,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  test_MA = pd.read_csv('v228_1_MA_obs.csv',index_col = 0)

In [3]:
test_MA

,orig.ident,nCount_RNA,nFeature_RNA,nCount_HTO,nFeature_HTO,percent.mito,percent.hb,HTO_maxID,HTO_secondID,HTO_margin,...,SCoV2_sum,SCoV2_load,cell_id,DoubSing,celltype,dbl_scDblFinder_num,dbl_doubletsum,dbl_doubletsumgr0,uniform_name_overview_temp,uniform_name_overview_keep
rn,,,,,,,,,,,,,,,,,,,,,
AGTATCTGTACGATGAATGGTTGGACA_3,SeuratProject,1004,448,72.0,8.0,9.295120,0.309837,SampleTag5,SampleTag12,2.406823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
AGTAAAGCCAATTATAACTGCATAGTA_3,SeuratProject,1210,573,216.0,10.0,7.373868,0.129366,SampleTag3,SampleTag2,1.272115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
GACGGATTACCATGCACAAACGTGTGA_3,SeuratProject,3077,980,121.0,10.0,13.925842,0.084914,SampleTag3,SampleTag8,0.198037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
ACCGGATAGTTGCGTACAACAAACTTT_3,SeuratProject,2004,797,98.0,8.0,14.053128,0.042845,SampleTag3,SampleTag2,0.584823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
AAGTAACCCACGACCACCAAGTTTACG_3,SeuratProject,1455,600,100.0,10.0,6.029332,0.054318,SampleTag5,SampleTag12,2.532280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ma_e14_blood_3_TCCTCGACAGGATTCT-1,ma,3090,968,NaN,NaN,1.825880,NaN,NaN,NaN,NaN,...,0.0,0.0,ma_e14_blood_3_TCCTCGACAGGATTCT-1,Singlet,Classical monocyte,0.0,0.0,False,NaN,False
ma_e14_blood_3_TCGGGCACAGGGTTGA-1,ma,3240,1204,NaN,NaN,1.306687,NaN,NaN,NaN,NaN,...,0.0,0.0,ma_e14_blood_3_TCGGGCACAGGGTTGA-1,Doublet,mDC,0.0,0.0,False,NaN,True
ma_e14_blood_3_TGGAGGATCCGATAAC-1,ma,3372,1295,NaN,NaN,1.820020,NaN,NaN,NaN,NaN,...,0.0,0.0,ma_e14_blood_3_TGGAGGATCCGATAAC-1,Singlet,mDC,0.0,0.0,False,NaN,False
ma_e14_blood_3_TTACCGCTCGTACCTC-1,ma,3622,1553,NaN,NaN,1.870748,NaN,NaN,NaN,NaN,...,0.0,0.0,ma_e14_blood_3_TTACCGCTCGTACCTC-1,Doublet,mDC,0.0,0.0,False,NaN,True
ma_e14_blood_3_TTTCCTCGTTCAGGTT-1,ma,3196,1454,NaN,NaN,2.207268,NaN,NaN,NaN,NaN,...,0.0,0.0,ma_e14_blood_3_TTTCCTCGTTCAGGTT-1,Doublet,B,0.0,0.0,False,NaN,True

In [10]:
test_PR = pd.read_csv('v228_1_PR_obs.csv',index_col = 0)

/tmp/ipykernel_279053/4168625218.py:1: DtypeWarning: Columns (8,9,11,12,13,14,15,16,18,19,21,22,23,24,25,26,27,29,30,31,32,33,34,35,37,39,40,41,42,43,44,67,69,78,79,80,96,97,100,101,102,107,108) have mixed types. Specify dtype option on import or set low_memory=False.
  test_PR = pd.read_csv('v228_1_PR_obs.csv',index_col = 0)

In [9]:
test_MA['uniform_name_overview_keep'].value_counts()

True     108009
False      6519
Name: uniform_name_overview_keep, dtype: int64

In [12]:
test_PR['uniform_name_overview_keep'].value_counts()

True     102711
False      5737
Name: uniform_name_overview_keep, dtype: int64